### ISSUE TITLE
Please add a license for this project

### ISSUE THREAD

**Issue by ccordoba12** [Winand/breadcrumbsaddressbar#1]
Hey @Winand, great project!! Thanks a lot for working on it!

We would like to use it in [Spyder](https://github.com/spyder-ide/spyder), so it'd be really nice if you could add a license for it. And hopefully one that is compatible with our own MIT license (i.e. an MIT or BSD license would be fine).

Thanks!

**Comment by Winand** [comment]
MIT license added.
Thanks for you attention to this little project.)

**Comment by ccordoba12** [comment]
Thanks a lot @Winand!

**Comment by roke-julian-lockhart** [comment]
> https://github.com/Winand/breadcrumbsaddressbar/issues/1#event-2373031826

For future reference, it's at [`blob/39109bc77a4beeed2c251a513649972486e42adf/LICENSE`](https://github.com/Winand/breadcrumbsaddressbar/blob/39109bc77a4beeed2c251a513649972486e42adf/LICENSE#L1-L21:~:text=MIT%20License,-Copyright%20(c)%202019).
